---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/manish-jangra/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-KFLUXINFRA-1211
