apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-as-a-service-hypershift-credentials
  namespace: clusters
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "false"
spec:
  dataFrom:
  - extract:
      key: integrations-output/terraform-resources/appsres09ue1/konflux-stage-eaas01/stage-eaas-serviceaccount
  - extract:
      key: stonesoup/staging/eaas/konflux-eaas-stage
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: hypershift
    template:
      data:
        aws_access_key_id: "{{ .aws_access_key_id }}"
        aws_secret_access_key: "{{ .aws_secret_access_key }}"
        pullSecret: "{{ .ocp_pull_secret }}"
        baseDomain: stage.konfluxeaas.com
        ssh-privatekey: unused
        ssh-publickey: unused

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-as-a-service-hypershift-oidc-credentials
  namespace: local-cluster
spec:
  dataFrom:
  - extract:
      key: integrations-output/terraform-resources/appsres09ue1/konflux-stage-eaas01/stage-eaas-serviceaccount
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: appsre-stonesoup-vault
  target:
    creationPolicy: Owner
    deletionPolicy: Delete
    name: hypershift-operator-oidc-provider-s3-credentials
    template:
      data:
        bucket: stage-eaas-bucket
        region: us-east-1
        credentials: |
          [default]
          aws_access_key_id={{ .aws_access_key_id }}
          aws_secret_access_key={{ .aws_secret_access_key }}
