apiVersion: operator.tekton.dev/v1alpha1
kind: TektonConfig
metadata:
  name: config
spec:
  pipeline:
    options:
      configMaps:
        config-defaults:
          data:
            default-pod-template: |
              nodeSelector:
                konflux-ci.dev/workload: konflux-tenants
              tolerations:
                - key: konflux-ci.dev/workload
                  operator: "Equal"
                  value: "konflux-tenants"
                  effect: "NoSchedule"
