---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6a-2xlarge
  namespace: proactive-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      run: m6a-2xlarge
  template:
    metadata:
      labels:
        run: m6a-2xlarge
    spec:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
        node.kubernetes.io/instance-type: m6a.2xlarge
      tolerations:
        - key: konflux-ci.dev/workload
          operator: "Equal"
          value: "konflux-tenants"
          effect: "NoSchedule"
      priorityClassName: pause-pods
      containers:
        - name: reserve-resources
          image: registry.k8s.io/pause
          resources:
            requests:
              memory: "22Gi"
              cpu: "5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6a-4xlarge
  namespace: proactive-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      run: m6a-4xlarge
  template:
    metadata:
      labels:
        run: m6a-4xlarge
    spec:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
        node.kubernetes.io/instance-type: m6a.4xlarge
      tolerations:
        - key: konflux-ci.dev/workload
          operator: "Equal"
          value: "konflux-tenants"
          effect: "NoSchedule"
      priorityClassName: pause-pods
      containers:
        - name: reserve-resources
          image: registry.k8s.io/pause
          resources:
            requests:
              memory: "45Gi"
              cpu: "10"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: c5d-4xlarge
  namespace: proactive-scaler
spec:
  replicas: 1
  selector:
    matchLabels:
      run: c5d-4xlarge
  template:
    metadata:
      labels:
        run: c5d-4xlarge
    spec:
      nodeSelector:
        konflux-ci.dev/storage: nvme
        node.kubernetes.io/instance-type: c5d.4xlarge
      tolerations:
        - key: konflux-ci.dev/storage
          operator: "Equal"
          value: "nvme"
          effect: "NoSchedule"
      priorityClassName: pause-pods
      containers:
        - name: reserve-resources
          image: registry.k8s.io/pause
          resources:
            requests:
              memory: "22Gi"
              cpu: "10"
