apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: multi-platform-controller

resources:
- ../../base/common
- host-config.yaml
- external-secrets.yaml
- https://github.com/konflux-ci/multi-platform-controller/deploy/operator?ref=b0ae512efadb81977c38f985e5a8f0f6321af568
- https://github.com/konflux-ci/multi-platform-controller/deploy/otp?ref=b0ae512efadb81977c38f985e5a8f0f6321af568

components:
  - ../../k-components/manager-resources

images:
- name: multi-platform-controller
  newName: quay.io/konflux-ci/multi-platform-controller
  newTag: b0ae512efadb81977c38f985e5a8f0f6321af568
- name: multi-platform-otp-server
  newName: quay.io/konflux-ci/multi-platform-controller-otp-service
  newTag: b0ae512efadb81977c38f985e5a8f0f6321af568

patches:
  - path: manager_resources_patch.yaml
